name: Build Gradle project
on: workflow_dispatch

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build with Gradle Wrapper
      run: ./gradlew build -x lint
    - name: 📦 Upload APK File
      uses: actions/upload-artifact@v3.1.3
      with:
        name: app_debug
        path: app/build/outputs/apk/debug/

 
